### ISSUE TITLE
doesn't work with RubyGems 2.0

### ISSUE THREAD

**Issue by rkh** [grosser/gem-dependent#9]
```
undefined method `find_matching' for #<Gem::SpecFetcher:0x007fccc925cae0>
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/gem-dependent-0.2.2/lib/rubygems/dependent.rb:70:in `all_specs_and_sources'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/gem-dependent-0.2.2/lib/rubygems/dependent.rb:10:in `block in find'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/gem-dependent-0.2.2/lib/rubygems/dependent.rb:104:in `with_changed_gem_source'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/gem-dependent-0.2.2/lib/rubygems/dependent.rb:9:in `find'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/gem-dependent-0.2.2/lib/rubygems/commands/dependent_command.rb:42:in `execute'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/command.rb:305:in `invoke_with_build_args'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/command_manager.rb:170:in `process_args'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/command_manager.rb:130:in `run'
/Users/konstantin/.rbenv/versions/2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/gem_runner.rb:60:in `run'
/Users/konstantin/.rbenv/versions/2.0.0-p195/bin/gem:21:in `<main>'
```
